### ISSUE TITLE
Home Assistant not recognizing device

### ISSUE THREAD

**Issue by Leomm04** [skyzhishui/magic_home#3]
Hi,
Why does HA not recognize my Magic Home RGB controller?

```
light:
  - platform: magic_home
    ip: 192.168.188.200
    dev_type: 5
```
